### ISSUE TITLE
Prototype pollution - merge

### ISSUE THREAD

**Issue by Hawkes81** [opendevtools/clearingnummer#649]
When running an npm audit, the following vulnerability was discovered;

https://www.npmjs.com/advisories/1666

Overview
Versions of merge before 2.1.1 are vulnerable to Prototype Pollution via _recursiveMerge .

Remediation
Upgrade to version 2.1.1 or later

**Comment by mikoleg** [comment]
Ran into the same issue. Would be great if anyone could look into this.

**Comment by believer** [comment]
The dependencies have been updated multiple times since this was reported. I can't see any issues when running `npm audit` so it seems like it's been solved 😄
